// full-stack-graphql/users/react-client/src/App.js
import { Routes, Route, Link } from 'react-router-dom';
import logo from './logo.svg';
import './App.css';
import Users from './components/Users';
import Home from './components/Home';
import AddUser from './components/AddUser';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <nav>
          <Link to="/" style={{ color: 'White' }}>
            Home |
          </Link>
          <Link to="/users" style={{ color: 'White' }}>
            Users |
          </Link>
          <Link to="/add-user" style={{ color: 'White' }}>
            Add User |
          </Link>
        </nav>
      </header>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/users" element={<Users />} />
        <Route path="/add-user" element={<AddUser />} />
      </Routes>
    </div>
  );
}

export default App;

// full-stack-graphql/users/vue-client/src/App.vue
<template>
  <div>
    <img alt="Vue logo" src="./assets/logo.png" />
    <h1>welcome to dashboard</h1>
    <nav>
      <router-link to="/">Home |</router-link>
      <router-link to="/users">Users |</router-link>
      <router-link to="/add-user">Add User |</router-link>
    </nav>
    <hr />
    <router-view />
  </div>
</template>

<script>
import Users from './components/Users';
export default {
  name: 'App',
  components: {
    Users,
  },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
