// full-stack-graphql/users-with-database/vue-client/src/components/AddUser.vue
<template>
  <div class="add-user">
    <h3>Add userrrrrrrrrrr</h3>
    <p>{{ addingDone }}</p>
    <form @submit.prevent="addUserHandler(user)">
      <div style="margin-bottom: 1rem">
        <label for="firstName">First Name</label>
        <input type="text" name="firstName" v-model="user.firstName" />
      </div>
      <div style="margin-bottom: 1rem">
        <label for="username">Username</label>
        <input type="text" name="username" v-model="user.username" />
      </div>
      <div style="margin-bottom: 1rem">
        <label for="favNumber">Fav Number</label>
        <input type="number" name="favNumber" v-model="user.favNumber" />
      </div>
      <div style="margin-bottom: 1rem">
        <label for="isActive">is active?</label>
        <input type="checkbox" name="isActive" v-model="user.isActive" />
      </div>
      <div style="margin-bottom: 1rem">
        <button type="submit">Edit User</button>
      </div>
    </form>
  </div>
</template>

<script>
import { gql } from '@apollo/client/core';
export default {
  data() {
    return {
      user: {
        firstName: '',
        username: '',
        favNumber: 0,
        isActive: false,
      },
      addingDone: '',
    };
  },
  methods: {
    addUserHandler(user) {
      this.$apollo.mutate({
        mutation: gql`
          mutation (
            $username: String!
            $firstName: String!
            $favNumber: Int!
            $isActive: Boolean!
          ) {
            addUser(
              username: $username
              firstName: $firstName
              isActive: $isActive
              favNumber: $favNumber
            )
          }
        `,
        variables: {
          firstName: user.firstName,
          username: user.username,
          favNumber: user.favNumber,
          isActive: user.isActive,
        },
      });
      this.addingDone = 'you have added the user successfully';
    },
  },
};
</script>

// full-stack-graphql/users-with-database/react-client/src/components/AddUser.jsx
import { useState } from 'react';
import { useMutation } from '@apollo/client';
import { useNavigate } from 'react-router-dom';
import mutations from '../api/mutations';
const AddUser = () => {
  const [formValues, setFormValues] = useState({
    firstName: '',
    username: '',
    favNumber: 0,
    isActive: false,
  });

  const handleChange = (event) => {
    const newObj = {
      ...formValues,
      [event.target.name]: event.target.value,
    };
    if (event.target.name === 'isActive') {
      newObj.isActive = !formValues.isActive;
    }
    setFormValues(newObj);
  };

  //navigate
  const navigate = useNavigate();

  // add user mutation
  const { addUser: addUserMutation } = mutations;
  const [addUserMutationFunc] = useMutation(addUserMutation);

  //submit form
  const handleSubmit = (event) => {
    event.preventDefault();
    addUserMutationFunc({
      variables: {
        ...formValues,
        favNumber: Number(formValues.favNumber),
      },
    });
    navigate('/users');
  };
  return (
    <div>
      <h1>You can add a user here</h1>
      <form>
        <div className="group">
          <label htmlFor="firstName">First Name: </label>
          <input
            type="text"
            name="firstName"
            value={formValues.firstName}
            onChange={handleChange}
          />
        </div>
        <hr />
        <div className="group">
          <label htmlFor="username">User Name: </label>
          <input
            type="text"
            name="username"
            value={formValues.username}
            onChange={handleChange}
          />
        </div>
        <hr />
        <div className="group">
          <label htmlFor="favNumber">Fav Number: </label>
          <input
            type="number"
            name="favNumber"
            value={formValues.favNumber}
            onChange={handleChange}
          />
        </div>
        <hr />
        <div className="group">
          <label htmlFor="isActive">Is User Active: </label>
          <input
            type="checkbox"
            name="isActive"
            value={formValues.isActive}
            onChange={handleChange}
          />
        </div>
        <hr />
        <div className="group">
          <button onClick={handleSubmit}>Add User</button>
        </div>
        <hr />
      </form>
    </div>
  );
};

export default AddUser;
