// full-stack-graphql/users/react-client/src/components/Users.jsx
import { useQuery } from '@apollo/client';
// import {gql} from '@apollo/client'
import User from './User';
import queries from '../api/queries';

// const getUsers = gql` query {
//     getAllUsers {
//       id
//       firstName
//       username
//       favNumber
//       isActive
//     }
//   }
// `;

const Users = () => {
  const { getUsers } = queries;
  const { loading, error, data } = useQuery(getUsers);
  return (
    <div>
      <h1>Welcome to Users</h1>
      {loading && <p> Loading Users ...</p>}
      {error && <p>Error: {error.message} </p>}
      {data &&
        data.getAllUsers &&
        data.getAllUsers.map((user, index) => {
          return <User key={index} {...user} />;
        })}
    </div>
  );
};

export default Users;

// full-stack-graphql/users/vue-client/src/components/Users.vue
<template>
  <div>
    <h3>users</h3>
    <div class="user" v-for="(user, index) in users" :key="index">
      <router-link :to="`/user/${user.id}`">{{ user.id }}</router-link>
      <h5>{{ user.username }} - {{ user.firstName }}</h5>
      <p>fav number: {{ user.favNumber }}</p>
      <p>is active: {{ user.isActive ? 'active' : 'NOT active' }}</p>
      <hr />
      <hr />
    </div>
  </div>
</template>

<script>
import { gql } from '@apollo/client/core';
export default {
  apollo: {
    users: {
      query: gql`
        query {
          getAllUsers {
            id
            firstName
            username
            isActive
            favNumber
          }
        }
      `,
      update: (data) => data.getAllUsers,
    },
  },
  data() {
    return {
      users: [],
    };
  },
};
</script>
